language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - android-19
  licenses:
  - 'android-.*'
jdk:
  - oraclejdk8
  - openjdk8
script:
  - ./gradlew clean
  - ./gradlew build
